### ISSUE TITLE
Add getter for entity name

### ISSUE THREAD

**Issue by rdb** [TheCheapestPixels/wecs#9]
It's possible to give an entity name in the constructor, so it would be useful if I could just do `entity.name` to retrieve it.

**Comment by Schwarzbaer** [comment]
There's nothing enforcing uniqueness of names (which were added for debug purposes), so would you like to get a list containing all matching entities?

This would also require iterating over all entities, so it may end up being an unexpectedly expensive operation unless we track entities by name as well, adding complexity that IMO isn't justified; I'd rather just discourage use of getting entities by name).

**Comment by rdb** [comment]
@Schwarzbaer No, I just want to do `entity.name` as a less ugly short-hand for `entity._uid.name`

**Comment by Schwarzbaer** [comment]
Implemented by 26a45c9
